### ISSUE TITLE
Add legend to hex map at end of Chapter 2

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#107]
* Add legend

**Comment by cnell-usgs** [comment]
Added a legend to the hex map (https://github.com/usgs-makerspace/temperature-prediction/pull/136). 
![Asset 2legends](https://user-images.githubusercontent.com/17803537/105649229-ebc97d80-5e74-11eb-82ad-f73535460ffc.png)

**Comment by cnell-usgs** [comment]
![image](https://user-images.githubusercontent.com/17803537/105661365-d19e9800-5e92-11eb-80fe-96b06836f234.png)
