### ISSUE TITLE
Address extra beeswarm "swarming" on scrolling steps that don't trigger changes

### ISSUE THREAD

**Issue by cnell-usgs** [usgs-makerspace/temperature-prediction#116]
the second half of my transitioning chart needs to calm down a bit. Need to go through as apply custom force changes with a lower alpha and higher alphaDecay for the transitions between model types

- [x] beeswarm forces adjustment
- [x]  stop extra ticking on steps that have no data changes
- [x] make sure beeswarm stay within plot constraints

**Comment by cnell-usgs** [comment]
To do this well, the initial chart drawing function needs to be re-worked so that it applies certain force parameters regardless of start step. This is necessary to give the simulation enough energy to put all the dots on the page in the first place, then the `updateChart` function uses step-specific forces to reposition dots

**Comment by hcorson-dosch-usgs** [comment]
@collnell - pretty sure you've covered all of this and that the issue can be closed?

**Comment by cnell-usgs** [comment]
Yes, although there's one pending thing I would like to address before release. If you scroll back up through the beeswarm, between the first rmse view and the error chart, the forces need to be tweaked so that the error chart doesn't appear to drift backwards. I think maybe I  need to reset the `forceCollide` there to null. Will get to this while out for review since it's fairly minor

**Comment by hcorson-dosch-usgs** [comment]
Sounds great 👍
