### ISSUE TITLE
Mobile nice-to-haves

### ISSUE THREAD

**Issue by limnoliver** [usgs-makerspace/temperature-prediction#127]
### Importance
- [x] reduce vertical space between icons

### Monitoring
- [x] make the GIF background the same black as the rest of the background
- [x] We don't get to see the bar graph in the matrix in the mobile version, so I think we should remove that part from the legend explainer. 
- [x] One more line of space between the GIF and the following paragraph.
- [x] One more line of space between the temperature time series line graph and the following paragraph.

**Comment by hcorson-dosch-usgs** [comment]
@ellenbechtel  if you could tackle 1, 4, and 5

I'll take on 2. Let's chat re: 3
