### ISSUE TITLE
On mobile, page wider than screen - slips sideways

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#129]
* Can we restrict the width of the page to the width of the device for phones and ipads?

**Comment by hcorson-dosch-usgs** [comment]
@ellenbechtel  - forgot to mention this issue. No idea if it's even possible to fix or how hard a fix it would be. Just wanted to throw it out there to consider

**Comment by ellenbechtel** [comment]
fixed it, I think!
