### ISSUE TITLE
Nice-to-haves prior to review

### ISSUE THREAD

**Issue by limnoliver** [usgs-makerspace/temperature-prediction#131]
- [x] fix case in figures captions. e.g., `Number of Temperature Measurements by year` to `Number of temperature measurements by year`.
- [x] add something to the text to distinguish the first "Monitoring" matrix from the second, because now the axes are different and the color is representing something else.
- [x] cleaned up section headers. Too much formatting with the bar, and I think there can be fewer sections. In Modeling, I suggest removing "Evaluating overall model accuracy" and "Model performance under restricted data availability" as a heading (just keep it all in "testing").
- [ ] Come up with some conclusion text in Modeling.  
- [ ] Resolve what we're calling PGDL. Knowledge-guided? Process-guided? Machine or deep learning?
- [x] keep "accurate" and "inaccurate" on the beeswarm the whole time.

**Comment by hcorson-dosch-usgs** [comment]
@ellenbechtel and @collnell  see also these 'nice-to-haves' identified by Sam

@ellenbechtel if you could look into 1, 2, and 3, that would be great

@limnoliver will tackle 4 and 5

@collnell  if you could address 6, that would be good

**Comment by hcorson-dosch-usgs** [comment]
@limnoliver - any final edits to the text that you wanted to make before review? or before I generate a .pdf of each chapter to include in IPDS?

**Comment by limnoliver** [comment]
For 5 - let's go with "knowledge-guided deep learning" for now, I think it's more accessible. It's used a few times, but process-guided will have to be changed in a few places. 

For 4 - Here's some proposed text for the conclusion:

"...(last text scroll)...the model is still able to make accurate predictions. These results give us confidence we will be able to use process-guided deep learning to expand the scale at which we make predictions."

"Additionally, these knowledge-guided machine learning models shine in new scenarios. When trained on only cold-season data, the model is able to predict warm-season dynamics. This is one piece of evidence that these models can make accurate predictions into the future where conditions might be different than we've ever seen before."

"To learn more about knowledge-guided deep learning, see recent publications by the USGS and collaborators in [lakes](https://agupubs.onlinelibrary.wiley.com/doi/pdfdirect/10.1029/2019WR024922) and [streams](https://arxiv.org/pdf/2009.12575.pdf)".

**Comment by hcorson-dosch-usgs** [comment]
perfect -- thanks, @limnoliver!
