### ISSUE TITLE
Accessibility Considerations

### ISSUE THREAD

**Issue by ellenbechtel** [usgs-makerspace/temperature-prediction#162]
See this guide for some accessibility considerations: http://www.storytellingwithdata.com/blog/2018/6/26/accessible-data-viz-is-better-data-viz
See this guide for writing alt text: https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81

- [x] write alt text for figures
- [ ] check for keyboard navigation ability
- [ ] navigate by screenreader to check
- [x] add aria labels

**Comment by hcorson-dosch-usgs** [comment]
Thanks for adding this to our issues list, Ellen!

**Comment by hcorson-dosch-usgs** [comment]
@ellenbechtel -- do we still need to add alt text for the figures? Or is that only done for images?
