### ISSUE TITLE
Step to release

### ISSUE THREAD

**Issue by cnell-usgs** [usgs-makerspace/temperature-prediction#166]
#### During development
- [x] Check that the 'robots' meta tag is added to stop indexing of beta (if the base template was used, this is included)
- [x] Push preliminary website to beta URL
- [x] Test on a phone; confirm there are no obvious issues

#### Final steps to release
- [x] Image optimization: Appropriately size and compress all image files (`png` and `jpg`) (https://squoosh.app/editor). 
- [x] Serve responsive, web-optimized images using 'srcset' with `.webp` as a primary and `.jpg` or `.png` as fall back  
- [x] Tweak code bundles and load order as needed for best performance and lazy loading
- [x] Test all links, set to open in new window
- [x] Verify the application works on a variety of devices and browsers (Browserstacko on mac)
- [x] Use lighthouse to measure performance and notice issues, SEO, and accessibility rating
- [x] Run mobile testing with iPhone Safari and Android Internet

#### During development
- [x] USGS  header and footer are used (included in base template)
- [x] Verify the application/visualization works on the following browsers: Chrome, Safari, Edge, Firefox, Samsung Internet, Internet Explorer 11 (redirect page included in base template) 
- [x] Check that components match [USWDS (U.S. Web Design System)](https://designsystem.digital.gov/)
- [x] Use [WAVE tool plugin](https://wave.webaim.org/) to verify that we are meeting 508 guidelines

#### During development
- [x] Register application with Google Analytics; create a 'property' under vizlab and add unique tags to app
- [x] Register application with Google Tag Manager: go to https://tagmanager.google.com/#/home and under the usgs-makerspace account create a new container; connect application to tag manager: go back to the application and the code that links the application to the new container; create 'auto tags' for page views, links, scroll depth (many other tag options exist, add as needed)
- [x] Verify USGS script tag exists: in the application make sure the 'general' USGS script tag is added (should already exist if you used the base template)
- [x] If custom dimensions required (and not using Tag Manager), verify that the custom code does what it should: make sure the application's Google ID is added to the plugging (the rest is setup in the Makerspace-base template). _Currently we add a couple custom dimensions through with use of the Vue Analytics plug in,
 - [x] Test that Google Analytics events/dimensions are working as expected.  You can use the [GA Debug Chrome plugin](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) to watch the outbound requests, or wait for data to show up in the Google Analytics UI

#### Final steps to release 
- [x] Setup specific events that you want to track for things such as image or section view. Again the preferred route is Google Tag Manager, but direct addition to the code is an option)

#### when 'steps to public release' start, so should the social media plan
- [x] Contact Web Comm to create social media campaign plan (need lead time in order to plan & get approved, ~2 weeks)
- [x] Decide what level of broadcast is needed (national accounts? just water? every platform? just Twitter?) - Sponsor + Web Comm should decide
- Generate social media content (GIFs, images, videos) to accompany posts ([video size guidelines](https://sproutsocial.com/insights/social-media-video-specs-guide/), [image size guidelines](https://sproutsocial.com/insights/social-media-image-sizes-guide/))
- [x]  Send Email to Group Sponsor and IIDD Director to inform them of communication plan and receive their input
- [x] Send Email to Group Sponsor and IIDD Director to inform them that the campaign is live

#### when given confirmation from the project champion that the product, in its current form, is ready
- [x] Check that the 'robots' meta tag is present to stop indexing of beta (if the base template was used, this is included)
- [x] Confirm that a link to the code (i.e. GitHub) is included
- [x] Confirm (with Project Champion) that links to previous visualizations are desired and what those should be and what images should be used. Include in the pre-footer.
- [x] Push preliminary website to beta URL (also needed for mobile & performance testing)
- [x] Preliminary stakeholder review of beta
- [x] Confirm public URL with Web Comm & Group Sponsor
- [ ] Data methods and references included somewhere in application
- [x] Contributors listed in website metadata
- [x] Enter meta data for social media tags
- [x] Check for registered product names. If found, add disclaimer 'Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government'
- [x] Final content review (IPDS for all hosted applications/visualizations)
- [x] Reconciliation of application from final content review
- [x] formal demo of application to Group Sponsor and IIDD Director (may be one or separate events)
- [x] Group sponsor ✔ (in email)
- [x] IIDD Director ✔ (in email)
- [x] Take off website "this is preliminary" banner (turns off automatically in with production build, but confirm )
- [x] Make Github repository 'readme' file presentable to the public - minimally include project overview and build instructions
- [x] Confirm all links work and go to the intended targets
- [ ] Update the Change Log to 'released'
- [ ] Update 'package.json' version number
- [x] Cut a release of the code
- [x] One more ✔ for final 'push to prod' -- approval from Group Sponsor who has approval from Water Mission Area Chief of Staff
- [x] Push to prod
- [x] Send Email to Group Sponsor and IIDD Director to alert that product is live
- [x] Celebrate 🎉

### Post-release

- [x] Team retrospective
- [ ] Web traffic analysis (probably wait a couple weeks)
- [x] Social media post analysis (probably wait a couple weeks)
- [x] Add content to makerspace internal site

**Comment by hcorson-dosch-usgs** [comment]
Thank you thank you thank you @collnell  for getting this set up!

**Comment by cnell-usgs** [comment]
No problem. If you want to tag team this, we can divide up the tasks in some way with @ellenbechtel, like performance/testing, social media, and engaging with sponsor and stakeholders/IPDS.
