### ISSUE TITLE
Have ch.3 headers fade in and out instead of scrolling

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#173]
would help w/ some instances where header + text doesn't really fit in open space.

might also help flubber feel more in the same chapter as beeswarm right when chapter heading changes

**Comment by hcorson-dosch-usgs** [comment]
This came up in review, so let's definitely implement this

**Comment by cnell-usgs** [comment]
When I adjusted the scrolling layout I also changed  the headers slightly. There was a big gap between the header and the next text that would make it disappear early. Now the headers are present consistently, which could address this comment, but maybe fade would still be better? What do you think @hcorson-dosch

**Comment by hcorson-dosch-usgs** [comment]
Hmm I agree that it is better now w/o the header disappearing early, but I still think having the headers face in and out would be best. As is, it still feels like flubber is part of the previous section when the header first scrolls up, even though flubber has updated along with beeswarm. And on mobile it would be great to not have the header taking up space as the user scrolls - right now, even w/ shorter text blocks, the header covers up some of flubber while the text is in the gap between the flubber and the beeswarm.

**Comment by hcorson-dosch-usgs** [comment]
Closed by #270
