### ISSUE TITLE
Add hex map code to folder in root dirfectory

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#184]
* plop R code to generate hex map and legend into folder in repo
* can be in own folder in root directory, or make new folder for code and subfolder for each application (e.g., Lindsay's svgify-matrix code, hexmap code, Sam's site processing code)

**Comment by cnell-usgs** [comment]
What's the best way to deal with the data here? It's made from a dataset with ~273,000 rows that I got from Sam. Should I include the `csv` or ask Sam for the code to download it? Is there a better way?

**Comment by hcorson-dosch-usgs** [comment]
maybe the code to download it is preferred, so that we aren't storing the data in the repo? @lindsayplatt  what would you typically do in this situation?

**Comment by lindsayplatt** [comment]
Yeah, typically you don't want to store data in the repo if it can be helped. Especially if they are large files. Code to recreate is great. Other alternatives to this are ScienceBase, GoogleDrive, or sometimes we use AWS S3. If the file can be recreated with code, either pointing to that code or including it is probably better.

**Comment by cnell-usgs** [comment]
@limnoliver see above. If you direct me to the some code I can fold it in with mine

**Comment by cnell-usgs** [comment]
Partially completed here: https://github.com/usgs-makerspace/temperature-prediction/pull/186

Needs observation  pull

**Comment by hcorson-dosch-usgs** [comment]
@limnoliver -- when you get the chance could you add your code to pull the CONUS temp observation counts to the `hex_map` subfolder?
