### ISSUE TITLE
Edit readme to describe source of temp observations and point to site-processing code

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#185]
* plop R code to get csv of unique DRB sites and count of temp observations per year into folder in repo
* can be in own folder in root directory, or make new folder for code and subfolder for each application (e.g., Lindsay's svgify-matrix code, Colleen's hexmap code, this temp. obs. / site processing code)

**Comment by hcorson-dosch-usgs** [comment]
@limnoliver -- not sure how we want to handle this piece, b/c the pull is pretty complex, and a totally separate repo. Is there any code that would make sense to include in the `preprocess-data` subfolder made in #245 ? The files you gave me I've placed in `preprocess-data/input_data`. One option would be to just add a blurb to the README.md indicating that those files were pulled from NWIS?

Also not sure if I need to include any source for `seg_outflow.csv` -- I pulled those from [Google Drive](https://drive.google.com/file/d/19T0jDbm3rXbu-FX38k9uRNT2g3XxPhfh/view?usp=sharing) -- what do you think?

**Comment by limnoliver** [comment]
Ahh yeah, a bit complicated.

I think we could post the entire DRB temperature observation file, point to the two repos that generate that data (2wp-temp-osbervations and delaware-model-prep), and the code that's used to process that data further for the viz. Not perfect, but the data are already published (from NWIS, WQP, and EcoSHEDS), so I don't feel too bad not pointing to a bundled up code package.

**Comment by hcorson-dosch-usgs** [comment]
> and the code that's used to process that data further for the viz. 

Where's that piece of code?
