### ISSUE TITLE
Add new block to end of Modeling chapter for new conclusion text

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#188]
* Now that the hexmap has been moved to the start of the Modeling chapter (with PR #187 ), need to re-write text at start of Modeling chapter
* Also need to add conclusion section

Note - may have to wait unto #187 is merged b/c that will move hexmap to Modeling chapter

**Comment by hcorson-dosch-usgs** [comment]
Per Sam's comment in #233 , we need to add a new section at the end and make the flubber and beeswarm scroll up before it starts. That section will include the text changes that are highlighted in yellow in [this doc](https://doimspp.sharepoint.com/:w:/s/IIDDStaff/EQxzYxo2mEhFv-nCY3SFLHIBC9LIOYvVilnqRzUsijbqbA?e=ZlaDsJ)

**Comment by hcorson-dosch-usgs** [comment]
UPDATED title to reflect need to add the new section at the end

**Comment by cnell-usgs** [comment]
Can you clarify what is meant by "make the flubber and beeswarm scroll up before it starts" @hcorson-dosch ?

**Comment by hcorson-dosch-usgs** [comment]
@collnell -- yes, sorry. I guess I mean that the final step of flubber and beeswarm would become sticky, and would be followed by a new sticky section with the header 'Conclusion', so as you scrolled through the conclusion section, flubber and beeswarm would be pushed out of your view. Does that make sense? Sorry if that's also a poor explanation
