### ISSUE TITLE
Address comments on temperature timeseries plot

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#197]
Comments:

- I think you are confusing two points with this chart. The main point seems to be that there is temperature variation – that is clear with the grey lines. The other point is to highlight the coldest and the warmest river, but the ‘coldest’ is also highly modified and not clearly the coldest except for parts of the summer. I suggest breaking the ideas apart into 2 charts one with the grey lines and coldest/warmest highlighted and a second with interesting examples of modified temperatures. 
- Can the locations of these two sites by shown on a small inset map? 
- ~Add 'Summer' to “warmest river reach” label~
- ~To “coldest reach” label - Add 'Summer'; this reach is the warmest reach in the fall (MH)~

**Comment by hcorson-dosch-usgs** [comment]
Note - I haven't addressed the first two comments - I think they would be too much work, and I'm not sure that the first suggestion would add that much to the viz. Thoughts @limnoliver ?

**Comment by limnoliver** [comment]
I think we can address the feedback about the two reaches we're highlighting with language changes. If we just note that the reservoir site is "one of the coldest in the summer", we've appropriately qualified that statement. I think it still highlights our point that the combo of natural variation and human modifications create a network of pretty diverse temperature signals.
