### ISSUE TITLE
double label on flubber

### ISSUE THREAD

**Issue by cnell-usgs** [usgs-makerspace/temperature-prediction#242]
Output layer

![image](https://user-images.githubusercontent.com/17803537/116951523-b5f31c80-ac4d-11eb-9536-1f068b29d769.png)

**Comment by hcorson-dosch-usgs** [comment]
what browser are you in? I don't see this in firefox or chrome? Or are you on desktop?

**Comment by cnell-usgs** [comment]
Hmm I think this was a momentary thing. I don't see it anymore. Sorry!
