### ISSUE TITLE
Address console errors?

### ISSUE THREAD

**Issue by lindsayplatt** [usgs-makerspace/temperature-prediction#255]
Likely not necessary to fix but I have noticed that there are a number of errors that pop up in the Console. I noticed this in my local build of #254 

Desktop:
![image](https://user-images.githubusercontent.com/13220910/118334102-860c0a80-b4d2-11eb-8280-b187b08963d1.png)

**Comment by cnell-usgs** [comment]
Yeah, I think this is related to how I added the connecting lines in the error chart part of the beeswarm. I think it's trying to draw the connections before there is any data to draw it, creating an error. I can potentially fix this by looking at the timing and steps that the `simJumpStart` function is called, or even just the ticking function for lines within in.

**Comment by hcorson-dosch-usgs** [comment]
closed by #272
