### ISSUE TITLE
Ch. 3: Implement y-axis transitions on scroll

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#47]
* Use the index value to transition the y-axis values on scroll

**Comment by cnell-usgs** [comment]
so close! If you watch the dots they make an obvious transition after the first scroll, but then the subsequent scrolls are moving ever so slightly. I think the issue to address is that the scaling function used to draw the first chart is not being applied to the data points in the subsequent charts, so the points are moving in pixels. 

![so close](https://user-images.githubusercontent.com/17803537/97886627-d110be00-1cf6-11eb-91f8-0a72bc368b1a.gif)

**Comment by hcorson-dosch-usgs** [comment]
Gah!! So exciting! that first transition is so cool.

**Comment by cnell-usgs** [comment]
finally got this working with the stacked dot approach
![histodot_transitions](https://user-images.githubusercontent.com/17803537/99263365-b05f6280-27e4-11eb-9721-917defd51123.gif)
