### ISSUE TITLE
Make final concluding visual for ch. 2

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#79]
* Modify crowbarred svg of matrix (data or 2019?) to highlight one area of matrix with low/no data and one area that is highly observed.

@ellenbechtel, @collnell I'm tabling this issue for now, since I don't think this transition visual is necessary w/ Sam's revised text

**Comment by cnell-usgs** [comment]
Ch. 2 complete
