### ISSUE TITLE
Wondering if it would help to use `<use>` to represent and re-use the stream network

### ISSUE THREAD

**Issue by jordansread** [usgs-makerspace/temperature-prediction#8]
The stream network is used in several different spots. I wonder if you've considered the `<use>` svg element which lets you re-use existing geometries that are found elsewhere in the DOM. It can help cut down on load times and bulk in general.

**Comment by hcorson-dosch-usgs** [comment]
I've never used that `<use>` element, but it does sound like it would apply here - at least for the two maps associated with the matrix. Currently, the stream network used for the stand-in ch. 1 map is actually a more simplified version. But for the two matrix maps there are a number of elements that are regenerated as svgs for the second map (stream network, invisible stream network with wider stroke for selection, delaware bay, etc.), so it would be great to instead just reuse the geometries from the first map in the second map.
