### ISSUE TITLE
Finalize ch 3 structure

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#87]
Base off of text chunks and flow outlined by Sam

**Comment by hcorson-dosch-usgs** [comment]
Sam's [proposed text](https://doimspp.sharepoint.com/sites/gs-wma-iidd-makerspace/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={28AF7BCE-11DB-40EE-A6F1-26BD0C81598F}). She says to feel free to move things around if things don't quite fit

**Comment by cnell-usgs** [comment]
Awesome!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I'll work on folding this in tomorrow

**Comment by cnell-usgs** [comment]
This task is largely complete. In https://github.com/usgs-makerspace/temperature-prediction/pull/102 we combined the flubber ann introduction to the error chart >> beeswarm transition and outlined the sequence of steps for the entire chapter.

 The work that remains in this scope is to:
- [x] refine text/narrative to match with step animations (with Sam), which specifically should include: 
- [x] finalizing the sequencing of back and forth flubber vs beeswarm transitions in the last ~10 or so text steps
- [x] and getting the timing of transitions to flow well with scrolling (consider placemen of scroll trigger and whether events are triggered on step enter vs exit)
- [x] double and triple checking backwards scrolling events

**Comment by cnell-usgs** [comment]
This has been completed with the addition of a conclusion section at the end of the beeswarm with "next steps"
