### ISSUE TITLE
Replace beeswarm/histodot data with new data

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [usgs-makerspace/temperature-prediction#88]
See what looks best

**Comment by cnell-usgs** [comment]
The beeswarm chart now contains RMSE data based on multiple stream reaches, from experiments using 100%, 2%, and .1% of training data (https://github.com/usgs-makerspace/temperature-prediction/pull/101). The data have been filtered to a random subset of stream reaches that were provided by @limnoliver to reduce the total number of points on the chart. When we get to around 800 points with these 3 experiments shown, performance becomes a big issue. 

Do we want to keep all 3 experiments? (vs just 2?)
What is the sweet spot of enough dots of the plot vs too many? There is a trade-off in the number of dots and dot size. With a lot of dots and they are somewhat bigger, the shape of the beeswarm starts being a big circle and we see no resolution of the data.

**Comment by limnoliver** [comment]
My initial thought is to just use the extremes for demonstration purposes (100% and 0.1%).

**Comment by limnoliver** [comment]
Okay - thinking about this more after reviewing all of the "Modeling" chapter. Wondering what @collnell and @hcorson-dosch think of the following suggestion: 

1. Only use the 0.1% data throughout the different model progressions (ANN through to PGDL) and skip all of the text in "model performance under restricted data availability". 
2. The "Modeling" chapter currently doesn't have a good conclusion, so the idea after the PGDL introduction at the end is to say, "PGDL methods seem promising compared to pure machine learning approaches, but how do we know PGDL can overcome our known data challenges, specifically the large space and time gaps in observations?" scroll and introduce the 100% dots on the beeswarm -- "The above model results were from an extreme test case where only 0.1% of the available data was used to train the model. The PGDL model performs even better when all data is used to train the model. This gives us confidence that the models can make accurate predictions across a wide range of data conditions." 

I think this achieves a simpler beeswarm visual throughout, a better conclusion, and shouldn't introduce too much work to accomplish (I hope?).

**Comment by hcorson-dosch-usgs** [comment]
Just a note to update this issue based on a convo w/ @limnoliver. For now we are going to keep the beeswarm part of the story as-is (e.g. _**not**_ changing it to only include 0.1% and a 'reveal' at the end that the shown model results were from an extreme case).

And Sam's thoughts on what dots @collnell should include in the version to be sent for review:
>As far as what dots to include, I think we could: 
> * just include 100% and 0.1% as two extreme test cases. still keep the text about putting the model to the test with reduced data availability. This will help keep the story simple/easy to interpret?
> * limit the dots to 1) summer, 2) completely or mostly observed months. I think that will reduce the dots in a reasonable way.

**Comment by cnell-usgs** [comment]
This is done with merge of https://github.com/usgs-makerspace/temperature-prediction/pull/137
